#!/usr/bin/env python3
"""
OCF CRM - Activity Types, Canonical Activities & Participant Allocation Migration

This is PHASE 1 of the historical Monday.com activity migration.

It performs ONLY:
    1. Create/reuse Activity Types
    2. Create/reuse canonical Activities
    3. Create/reuse participant Activity Type allocations

It DOES NOT create:
    - sessions
    - session registrations
    - attendance

Those will be migrated separately after historical session times are confirmed.

SOURCE
------
Use the participant preview CSV generated by:
    preview_ocf_monday_activity_sessions.py

Example:
    ocf_monday_activity_sessions_preview_20260913_213900_participants.csv

DEFAULT MODE IS PREVIEW.
No database changes are made unless --commit is supplied.

PREVIEW:
    py -3.14 .\migrate_ocf_activity_allocations.py `
      --participants-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_participants.csv"

COMMIT:
    py -3.14 .\migrate_ocf_activity_allocations.py `
      --participants-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_participants.csv" `
      --commit

CONNECTION
----------
Uses:
    OCF_MYSQL_CONNECTION_STRING

The connection string format is:
    mysql://USER:PASSWORD@HOST:3306/DATABASE?charset=utf8mb4
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import uuid
from collections import Counter, defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, unquote, urlparse

import pymysql


DEFAULT_CONNECTION_STRING = os.getenv(
    "OCF_MYSQL_CONNECTION_STRING",
    "mysql://YOUR_DB_USER:YOUR_DB_PASSWORD@YOUR_DB_HOST:3306/YOUR_DB_NAME?charset=utf8mb4",
)

MIGRATION_NAME = "OCF_MONDAY_ACTIVITY_ALLOCATIONS_V1"

# Canonical Activity Types to exist in OCF.
DESIRED_ACTIVITY_TYPES = {
    "Cricket": "Historical OCF cricket programme.",
    "FootBall": "Historical OCF football programme.",
    "Youth Club": "Historical OCF youth club programme.",
    "HAF": "Historical OCF HAF programme.",
    "XLR8": "Historical OCF XLR8 programme.",
}

# Canonical Activities. 30 Monday exports are historical periods/runs of these
# activities, NOT 30 separate OCF activities.
CANONICAL_ACTIVITIES = [
    # Existing OCF record should be reused.
    {"name": "Girl's Cricket", "activity_type": "Cricket", "source_programme": "Girls Cricket"},

    # Activity only; user confirmed there is no historical Boys Cricket attendance.
    {"name": "Boys Cricket", "activity_type": "Cricket", "source_programme": "Boys Cricket"},

    {"name": "Girls Football", "activity_type": "FootBall", "source_programme": "Girls Football"},
    {"name": "Boys Football", "activity_type": "FootBall", "source_programme": "Boys Football"},

    {"name": "Girls Youth Club", "activity_type": "Youth Club", "source_programme": "Girls Youth Club"},
    {"name": "Youth Club (Mixed)", "activity_type": "Youth Club", "source_programme": "Youth Club (Mixed)"},

    {"name": "HAF", "activity_type": "HAF", "source_programme": "HAF"},
    {"name": "XLR8", "activity_type": "XLR8", "source_programme": "XLR8"},
]

# Source programme -> Activity Type allocation.
SOURCE_PROGRAMME_TO_TYPE = {
    "Girls Cricket": "Cricket",
    "Boys Cricket": "Cricket",
    "Girls Football": "FootBall",
    "Boys Football": "FootBall",
    "Girls Youth Club": "Youth Club",
    "Youth Club (Mixed)": "Youth Club",
    "HAF": "HAF",
    "XLR8": "XLR8",
}


def connect_mysql(connection_string: str):
    parsed = urlparse(connection_string)
    if parsed.scheme not in {"mysql", "mysql+pymysql"}:
        raise ValueError("Connection string must begin mysql://")
    if not parsed.hostname or not parsed.username or not parsed.path.strip("/"):
        raise ValueError("Connection string is incomplete.")

    query = parse_qs(parsed.query)
    kwargs = {
        "host": parsed.hostname,
        "port": parsed.port or 3306,
        "user": unquote(parsed.username),
        "password": unquote(parsed.password or ""),
        "database": parsed.path.lstrip("/"),
        "charset": query.get("charset", ["utf8mb4"])[0],
        "autocommit": False,
        "cursorclass": pymysql.cursors.DictCursor,
        "connect_timeout": 15,
        "read_timeout": 60,
        "write_timeout": 60,
    }
    if query.get("ssl", ["false"])[0].lower() in {"1", "true", "yes"}:
        kwargs["ssl"] = {}

    conn = pymysql.connect(**kwargs)
    with conn.cursor() as cur:
        cur.execute("SET time_zone = '+00:00'")
    return conn


def table_exists(conn, table: str) -> bool:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT COUNT(*) AS cnt
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = %s
            """,
            (table,),
        )
        return cur.fetchone()["cnt"] == 1


def check_schema(conn) -> None:
    required = {
        "activity_types",
        "activities",
        "participants",
        "participant_activity_types",
    }
    missing = [t for t in required if not table_exists(conn, t)]
    if missing:
        raise RuntimeError(f"Missing required OCF tables: {', '.join(missing)}")


def clean(value: Any) -> str:
    return "" if value is None else str(value).strip()


def norm(value: Any) -> str:
    return clean(value).casefold()


def load_source_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        required = {
            "source_programme",
            "match_status",
            "matched_participant_id",
            "matched_ocf_id",
            "matched_name",
            "source_status",
        }
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise RuntimeError(
                "Participants CSV is missing required columns: " + ", ".join(sorted(missing))
            )
        return list(reader)


def load_activity_types(conn) -> list[dict[str, Any]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, name, description, status
            FROM activity_types
            ORDER BY name, id
            """
        )
        return cur.fetchall()


def resolve_activity_type(existing_rows, desired_name: str):
    matches = [r for r in existing_rows if norm(r["name"]) == norm(desired_name)]
    if len(matches) > 1:
        return "BLOCK_AMBIGUOUS", None
    if len(matches) == 1:
        return "REUSE", matches[0]
    return "CREATE", None


def load_activities(conn) -> list[dict[str, Any]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                id,
                activity_type_id,
                name,
                description,
                status,
                venue,
                start_date,
                end_date,
                start_time,
                end_time,
                capacity
            FROM activities
            ORDER BY name, id
            """
        )
        return cur.fetchall()


def resolve_activity(existing_rows, desired_name: str, activity_type_id: str):
    name_matches = [r for r in existing_rows if norm(r["name"]) == norm(desired_name)]

    same_type = [
        r for r in name_matches
        if clean(r.get("activity_type_id")) == clean(activity_type_id)
    ]

    if len(same_type) > 1:
        return "BLOCK_AMBIGUOUS", None

    if len(same_type) == 1:
        return "REUSE", same_type[0]

    if name_matches:
        # Same name already exists but belongs to another/null activity type.
        return "BLOCK_NAME_CONFLICT", name_matches[0]

    return "CREATE", None


def participant_ids_exist(conn, participant_ids: set[str]) -> set[str]:
    if not participant_ids:
        return set()

    found = set()
    ids = list(participant_ids)

    # Chunk to avoid giant IN lists.
    for i in range(0, len(ids), 500):
        chunk = ids[i:i+500]
        placeholders = ",".join(["%s"] * len(chunk))
        with conn.cursor() as cur:
            cur.execute(
                f"SELECT id FROM participants WHERE id IN ({placeholders})",
                chunk,
            )
            found.update(str(r["id"]) for r in cur.fetchall())
    return found


def load_existing_allocations(conn):
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT
                pat.id,
                pat.participant_id,
                pat.activity_type_id,
                pat.active,
                pat.assigned_by,
                pat.assigned_at,
                pat.updated_at
            FROM participant_activity_types pat
            """
        )
        return cur.fetchall()


def build_allocation_candidates(source_rows: list[dict[str, str]]):
    """
    One participant can appear in many quarterly exports for the same programme.
    OCF stores allocation at Activity Type level, so collapse to:
        participant_id + activity_type_name
    """
    evidence = defaultdict(lambda: {
        "programmes": set(),
        "source_statuses": set(),
        "source_files": set(),
        "matched_ocf_id": "",
        "matched_name": "",
        "source_rows": 0,
    })

    review_rows = []

    for row in source_rows:
        programme = clean(row.get("source_programme"))
        match_status = clean(row.get("match_status"))
        participant_id = clean(row.get("matched_participant_id"))

        if programme not in SOURCE_PROGRAMME_TO_TYPE:
            review_rows.append({
                "source_programme": programme,
                "reason": "Unknown source programme mapping",
                "match_status": match_status,
                "matched_ocf_id": clean(row.get("matched_ocf_id")),
                "matched_name": clean(row.get("matched_name")),
            })
            continue

        if match_status != "MATCHED_NAME_DOB" or not participant_id:
            # Do not allocate unmatched/ambiguous source participants.
            continue

        activity_type_name = SOURCE_PROGRAMME_TO_TYPE[programme]
        key = (participant_id, activity_type_name)

        item = evidence[key]
        item["programmes"].add(programme)

        source_status = clean(row.get("source_status"))
        if source_status:
            item["source_statuses"].add(source_status)

        source_file = clean(row.get("file"))
        if source_file:
            item["source_files"].add(source_file)

        item["matched_ocf_id"] = clean(row.get("matched_ocf_id"))
        item["matched_name"] = clean(row.get("matched_name"))
        item["source_rows"] += 1

    return evidence, review_rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return

    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def parse_args():
    p = argparse.ArgumentParser(
        description="Migrate OCF canonical activities and participant Activity Type allocations."
    )
    p.add_argument("--participants-csv", required=True)
    p.add_argument("--output-dir", default=".")
    p.add_argument("--connection-string", default=DEFAULT_CONNECTION_STRING)
    p.add_argument("--commit", action="store_true")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    participants_csv = Path(args.participants_csv).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not participants_csv.exists():
        print(f"ERROR: participants CSV not found: {participants_csv}", file=sys.stderr)
        return 2

    if "YOUR_DB_" in args.connection_string:
        print("ERROR: set OCF_MYSQL_CONNECTION_STRING first.", file=sys.stderr)
        return 3

    source_rows = load_source_rows(participants_csv)
    allocation_evidence, source_review_rows = build_allocation_candidates(source_rows)

    conn = connect_mysql(args.connection_string)

    try:
        check_schema(conn)

        existing_types = load_activity_types(conn)
        existing_activities = load_activities(conn)

        # ---------------------------------------------------------------
        # Plan Activity Types
        # ---------------------------------------------------------------
        type_plan = []
        type_ids = {}

        for name, description in DESIRED_ACTIVITY_TYPES.items():
            action, existing = resolve_activity_type(existing_types, name)

            if action == "REUSE":
                type_id = str(existing["id"])
                type_ids[name] = type_id
                type_plan.append({
                    "activity_type": name,
                    "action": "REUSE",
                    "id": type_id,
                    "existing_status": existing["status"],
                    "notes": "",
                })
            elif action == "CREATE":
                type_id = str(uuid.uuid4())
                type_ids[name] = type_id
                type_plan.append({
                    "activity_type": name,
                    "action": "CREATE",
                    "id": type_id,
                    "existing_status": "",
                    "notes": description,
                })
            else:
                type_plan.append({
                    "activity_type": name,
                    "action": action,
                    "id": "",
                    "existing_status": "",
                    "notes": "Multiple activity_types with the same normalized name.",
                })

        blocked_types = [r for r in type_plan if r["action"].startswith("BLOCK")]
        if blocked_types:
            raise RuntimeError(
                "Activity Type planning found ambiguous/conflicting rows. "
                "Review the generated audit before any commit."
            )

        # ---------------------------------------------------------------
        # Plan Activities
        # ---------------------------------------------------------------
        activity_plan = []

        for desired in CANONICAL_ACTIVITIES:
            type_id = type_ids[desired["activity_type"]]
            action, existing = resolve_activity(
                existing_activities,
                desired["name"],
                type_id,
            )

            if action == "REUSE":
                activity_id = str(existing["id"])
                activity_plan.append({
                    "activity": desired["name"],
                    "activity_type": desired["activity_type"],
                    "source_programme": desired["source_programme"],
                    "action": "REUSE",
                    "id": activity_id,
                    "existing_type_id": clean(existing.get("activity_type_id")),
                    "notes": "Existing canonical activity reused.",
                })
            elif action == "CREATE":
                activity_id = str(uuid.uuid4())
                activity_plan.append({
                    "activity": desired["name"],
                    "activity_type": desired["activity_type"],
                    "source_programme": desired["source_programme"],
                    "action": "CREATE",
                    "id": activity_id,
                    "existing_type_id": "",
                    "notes": (
                        "Historical Monday.com canonical activity. "
                        "Session timetable fields intentionally left NULL in Phase 1."
                    ),
                })
            else:
                activity_plan.append({
                    "activity": desired["name"],
                    "activity_type": desired["activity_type"],
                    "source_programme": desired["source_programme"],
                    "action": action,
                    "id": clean(existing.get("id")) if existing else "",
                    "existing_type_id": clean(existing.get("activity_type_id")) if existing else "",
                    "notes": (
                        "An activity with this canonical name already exists under a different "
                        "or ambiguous Activity Type. Manual review required."
                    ),
                })

        blocked_activities = [r for r in activity_plan if r["action"].startswith("BLOCK")]
        if blocked_activities:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            write_csv(
                output_dir / f"ocf_activity_allocation_{timestamp}_activity_conflicts.csv",
                blocked_activities,
            )
            raise RuntimeError(
                "Canonical Activity planning found a name/type conflict. "
                "No database changes were made."
            )

        # ---------------------------------------------------------------
        # Plan participant allocations
        # ---------------------------------------------------------------
        participant_ids = {key[0] for key in allocation_evidence}
        valid_participant_ids = participant_ids_exist(conn, participant_ids)

        existing_allocs = load_existing_allocations(conn)
        existing_by_key = defaultdict(list)
        for row in existing_allocs:
            existing_by_key[
                (str(row["participant_id"]), str(row["activity_type_id"]))
            ].append(row)

        allocation_plan = []
        missing_participant_count = 0
        inactive_existing_count = 0

        for (participant_id, type_name), evidence in sorted(
            allocation_evidence.items(),
            key=lambda item: (item[0][1], item[1]["matched_ocf_id"], item[1]["matched_name"]),
        ):
            type_id = type_ids[type_name]

            if participant_id not in valid_participant_ids:
                missing_participant_count += 1
                allocation_plan.append({
                    "participant_id": participant_id,
                    "ocf_id": evidence["matched_ocf_id"],
                    "participant_name": evidence["matched_name"],
                    "activity_type": type_name,
                    "activity_type_id": type_id,
                    "action": "BLOCK_PARTICIPANT_NOT_FOUND",
                    "source_programmes": "; ".join(sorted(evidence["programmes"])),
                    "source_statuses": "; ".join(sorted(evidence["source_statuses"])),
                    "source_files": len(evidence["source_files"]),
                    "source_rows": evidence["source_rows"],
                    "notes": "Matched participant ID from preview no longer exists in participants table.",
                })
                continue

            current = existing_by_key.get((participant_id, type_id), [])

            if len(current) > 1:
                allocation_plan.append({
                    "participant_id": participant_id,
                    "ocf_id": evidence["matched_ocf_id"],
                    "participant_name": evidence["matched_name"],
                    "activity_type": type_name,
                    "activity_type_id": type_id,
                    "action": "BLOCK_DUPLICATE_EXISTING_ALLOCATIONS",
                    "source_programmes": "; ".join(sorted(evidence["programmes"])),
                    "source_statuses": "; ".join(sorted(evidence["source_statuses"])),
                    "source_files": len(evidence["source_files"]),
                    "source_rows": evidence["source_rows"],
                    "notes": f"{len(current)} existing participant_activity_types rows found.",
                })
                continue

            if len(current) == 1:
                row = current[0]
                if int(row["active"]) == 1:
                    action = "REUSE_ACTIVE"
                    notes = "Existing active allocation retained."
                else:
                    # Do not silently reactivate an allocation that somebody deliberately disabled.
                    inactive_existing_count += 1
                    action = "REVIEW_EXISTING_INACTIVE"
                    notes = (
                        "Historical source supports this Activity Type, but the existing CRM "
                        "allocation is inactive. Script will NOT reactivate it automatically."
                    )

                allocation_plan.append({
                    "participant_id": participant_id,
                    "ocf_id": evidence["matched_ocf_id"],
                    "participant_name": evidence["matched_name"],
                    "activity_type": type_name,
                    "activity_type_id": type_id,
                    "action": action,
                    "source_programmes": "; ".join(sorted(evidence["programmes"])),
                    "source_statuses": "; ".join(sorted(evidence["source_statuses"])),
                    "source_files": len(evidence["source_files"]),
                    "source_rows": evidence["source_rows"],
                    "notes": notes,
                })
                continue

            allocation_plan.append({
                "participant_id": participant_id,
                "ocf_id": evidence["matched_ocf_id"],
                "participant_name": evidence["matched_name"],
                "activity_type": type_name,
                "activity_type_id": type_id,
                "action": "CREATE_ACTIVE",
                "source_programmes": "; ".join(sorted(evidence["programmes"])),
                "source_statuses": "; ".join(sorted(evidence["source_statuses"])),
                "source_files": len(evidence["source_files"]),
                "source_rows": evidence["source_rows"],
                "notes": "Create active Activity Type allocation from historical Monday roster evidence.",
            })

        blocking_allocs = [
            r for r in allocation_plan
            if r["action"].startswith("BLOCK_")
        ]

        # ---------------------------------------------------------------
        # Write audit BEFORE commit decision
        # ---------------------------------------------------------------
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        mode = "commit" if args.commit else "preview"
        prefix = output_dir / f"ocf_activity_allocation_{mode}_{timestamp}"

        type_csv = Path(str(prefix) + "_activity_types.csv")
        activity_csv = Path(str(prefix) + "_activities.csv")
        allocation_csv = Path(str(prefix) + "_allocations.csv")
        source_review_csv = Path(str(prefix) + "_source_review.csv")

        write_csv(type_csv, type_plan)
        write_csv(activity_csv, activity_plan)
        write_csv(allocation_csv, allocation_plan)
        write_csv(source_review_csv, source_review_rows)

        counts = Counter(r["action"] for r in allocation_plan)

        print()
        print("OCF Activity Type / Activity / Allocation Migration")
        print("----------------------------------------------------")
        print(f"Source preview roster rows:        {len(source_rows)}")
        print(f"Unique matched allocation candidates:{len(allocation_plan):>6}")
        print()
        print("Activity Types")
        print(f"  Reuse:                           {sum(r['action']=='REUSE' for r in type_plan)}")
        print(f"  Create:                          {sum(r['action']=='CREATE' for r in type_plan)}")
        print()
        print("Canonical Activities")
        print(f"  Reuse:                           {sum(r['action']=='REUSE' for r in activity_plan)}")
        print(f"  Create:                          {sum(r['action']=='CREATE' for r in activity_plan)}")
        print()
        print("Participant Activity Type allocations")
        print(f"  New active allocations:          {counts['CREATE_ACTIVE']}")
        print(f"  Existing active reused:          {counts['REUSE_ACTIVE']}")
        print(f"  Existing inactive for review:    {counts['REVIEW_EXISTING_INACTIVE']}")
        print(f"  Blocking allocation problems:    {len(blocking_allocs)}")
        print()
        print("Unmatched/ambiguous source rows")
        print("  Not included in allocations. They remain in the earlier participant review CSV.")
        print()
        print("Audit files:")
        print(f"  {type_csv}")
        print(f"  {activity_csv}")
        print(f"  {allocation_csv}")
        if source_review_rows:
            print(f"  {source_review_csv}")
        print()

        if blocking_allocs:
            print("STOP: blocking allocation problems were found. Database was NOT changed.")
            conn.rollback()
            return 10

        # ---------------------------------------------------------------
        # Preview stops here.
        # ---------------------------------------------------------------
        if not args.commit:
            conn.rollback()
            print("PREVIEW COMPLETE: database was NOT changed.")
            print("Review the audit CSVs before rerunning with --commit.")
            return 0

        # ---------------------------------------------------------------
        # COMMIT - one transaction
        # ---------------------------------------------------------------
        conn.begin()

        try:
            # Activity Types
            for row in type_plan:
                if row["action"] != "CREATE":
                    continue
                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO activity_types
                            (id, name, description, status)
                        VALUES
                            (%s, %s, %s, 'Active')
                        """,
                        (
                            row["id"],
                            row["activity_type"],
                            DESIRED_ACTIVITY_TYPES[row["activity_type"]],
                        ),
                    )

            # Activities
            activity_desired_by_name = {a["name"]: a for a in CANONICAL_ACTIVITIES}

            for row in activity_plan:
                if row["action"] != "CREATE":
                    continue

                desired = activity_desired_by_name[row["activity"]]
                type_id = type_ids[desired["activity_type"]]

                with conn.cursor() as cur:
                    cur.execute(
                        """
                        INSERT INTO activities
                            (
                                id,
                                activity_type_id,
                                name,
                                description,
                                status,
                                venue,
                                start_date,
                                end_date,
                                start_time,
                                end_time,
                                capacity,
                                notes
                            )
                        VALUES
                            (
                                %s, %s, %s, %s, 'Active',
                                NULL, NULL, NULL, NULL, NULL, NULL, %s
                            )
                        """,
                        (
                            row["id"],
                            type_id,
                            desired["name"],
                            "Historical Monday.com canonical activity.",
                            f"{MIGRATION_NAME}; source programme={desired['source_programme']}",
                        ),
                    )

            # Participant Activity Type allocations.
            for row in allocation_plan:
                if row["action"] != "CREATE_ACTIVE":
                    continue

                with conn.cursor() as cur:
                    # Recheck inside transaction for idempotency.
                    cur.execute(
                        """
                        SELECT id, active
                        FROM participant_activity_types
                        WHERE participant_id = %s
                          AND activity_type_id = %s
                        """,
                        (row["participant_id"], row["activity_type_id"]),
                    )
                    current = cur.fetchall()

                    if current:
                        # Another process/user may have added it since preview.
                        # Never create duplicates or silently alter an inactive row.
                        continue

                    cur.execute(
                        """
                        INSERT INTO participant_activity_types
                            (
                                id,
                                participant_id,
                                activity_type_id,
                                active,
                                assigned_by
                            )
                        VALUES
                            (%s, %s, %s, 1, NULL)
                        """,
                        (
                            str(uuid.uuid4()),
                            row["participant_id"],
                            row["activity_type_id"],
                        ),
                    )

            conn.commit()

        except Exception:
            conn.rollback()
            raise

        print("COMMIT COMPLETE.")
        print("Created/reused Activity Types, canonical Activities, and participant Activity Type allocations.")
        print("No sessions, session registrations, or attendance were changed.")
        return 0

    except Exception as exc:
        try:
            conn.rollback()
        except Exception:
            pass
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
