#!/usr/bin/env python3
"""
OCF CRM - Monday.com Participant Migration (Excel -> MySQL)

Designed for the OCF CRM schema reviewed from the PHP/MySQL backend.

Safety:
- PREVIEW is the default. It does not write to the database.
- Use --commit only after reviewing the preview CSV/summary.
- Girls and Boys can be migrated as separate batches into the SAME OCF participant tables.
- Monday "Status" is NOT mapped to OCF registration_status.
- Existing/possible duplicate participants are skipped for review.
- Safeguarding concerns are never silently discarded: meaningful concerns block the row for review.
- Legacy signature URLs are not inserted into the signatures table because that table expects a
  private stored file + hash, not an external Monday.com URL.

Dependencies:
    py -m pip install openpyxl PyMySQL

Recommended connection setup (PowerShell):
    $env:OCF_MYSQL_CONNECTION_STRING="mysql://DB_USER:DB_PASSWORD@DB_HOST:3306/DB_NAME?charset=utf8mb4"

If the password contains @, :, /, #, ? or other URL special characters, URL-encode it.

Preview:
    python migrate_ocf_monday_participants.py --source "Girls.xlsx" --batch girls

Commit after reviewing preview:
    python migrate_ocf_monday_participants.py --source "Girls.xlsx" --batch girls --commit

For the redacted sample workbook only:
    python migrate_ocf_monday_participants.py --source "sample.xlsx" --batch girls --redacted-sample
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import uuid
from dataclasses import dataclass, field
from datetime import date, datetime, time
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import parse_qs, unquote, urlparse

import pymysql
from pymysql.connections import Connection
from openpyxl import load_workbook
from openpyxl.utils.datetime import from_excel


# ---------------------------------------------------------------------------
# CONNECTION STRING
# ---------------------------------------------------------------------------

DEFAULT_CONNECTION_STRING = os.getenv(
    "OCF_MYSQL_CONNECTION_STRING",
    "mysql://uxj77qdlcbwyu:+Ld(k24@##*u@35.214.66.8:3306/dbgonmlutvgyq5?charset=utf8mb4",
)

MIGRATION_NAME = "OCF_MONDAY_PARTICIPANTS_V1"
AUDIT_ACTION = "ParticipantMigratedMonday"

# The Monday export does not have a participant mobile column.
# For under-18s, the primary guardian mobile can safely act as the CRM primary contact.
# For adults, the default is to REQUIRE REVIEW rather than silently use a guardian's number.
ALLOW_GUARDIAN_PHONE_FOR_18_PLUS_DEFAULT = False

# OCF participant registration generated by this historical import.
# These are legacy registration-form records, so they are imported as Full/Full.
REGISTRATION_TYPE = "Full"
REGISTRATION_STATUS = "Full"
REGISTRATION_SOURCE = "Staff"

UK_POSTCODE_RE = re.compile(
    r"\b(GIR\s?0AA|[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2})\b",
    re.IGNORECASE,
)

NEGATIVE_TEXT = {
    "no",
    "none",
    "n/a",
    "na",
    "nil",
    "nope",
    "not applicable",
    "nothing",
    "none known",
    "no known",
}

YES_TEXT = {"yes", "y", "true", "1", "granted", "accepted"}
NO_TEXT = {"no", "n", "false", "0", "declined", "not accepted"}

SAMPLE_REDACTED_VALUE = "34"


@dataclass
class PreparedParticipant:
    source_row: int
    batch: str
    full_name: str = ""
    first_name: str = ""
    last_name: str = ""
    date_of_birth: str | None = None
    date_form_completed: str | None = None
    age_at_form: int | None = None
    gender: str | None = None
    school_name: str | None = None
    home_address: str | None = None
    postcode: str | None = None
    mobile_number: str | None = None
    mobile_source: str | None = None
    guardian_name: str | None = None
    guardian_phone: str | None = None
    guardian_email: str | None = None
    guardian_relationship: str | None = None
    emergency_name: str | None = None
    emergency_relationship: str | None = None
    emergency_phone: str | None = None
    emergency_pickup_authorised: bool | None = None
    health: dict[str, Any] = field(default_factory=dict)
    ethnic_origin: str | None = None
    religion: str | None = None
    communication: dict[str, bool] | None = None
    photo_video_consent: bool | None = None
    gdpr_personal_data_consent: bool | None = None
    anonymised_reporting_consent: bool | None = None
    source_status: str | None = None
    signature_url: str | None = None
    consent_form_value: str | None = None
    notes_value: str | None = None
    files_value: str | None = None
    blockers: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    duplicate_matches: list[dict[str, Any]] = field(default_factory=list)
    preview_ocf_id: str | None = None
    inserted_ocf_id: str | None = None
    inserted_participant_id: str | None = None

    @property
    def ready(self) -> bool:
        return not self.blockers and not self.duplicate_matches


# ---------------------------------------------------------------------------
# BASIC NORMALISATION
# ---------------------------------------------------------------------------

def clean_text(value: Any, *, redacted_sample: bool = False) -> str | None:
    if value is None:
        return None

    if isinstance(value, datetime):
        value = value.isoformat(sep=" ")

    text = re.sub(r"\s+", " ", str(value)).strip()
    if not text:
        return None

    if redacted_sample and text == SAMPLE_REDACTED_VALUE:
        return None

    return text


def normalize_name(value: Any, *, redacted_sample: bool = False) -> str | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None
    return re.sub(r"\s+", " ", text).strip()


def split_participant_name(full_name: str) -> tuple[str | None, str | None]:
    """
    OCF ID requires first AND last initial.
    Do not invent a surname for single-name records.
    """
    parts = [p for p in re.split(r"\s+", full_name.strip()) if p]
    if len(parts) < 2:
        return None, None
    return parts[0], " ".join(parts[1:])


def normalize_gender(value: Any, *, redacted_sample: bool = False) -> str | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None
    key = text.casefold()
    mapping = {
        "girl": "Female",
        "female": "Female",
        "woman": "Female",
        "boy": "Male",
        "male": "Male",
        "man": "Male",
        "non-binary": "Non-Binary",
        "nonbinary": "Non-Binary",
        "prefer not to say": "Prefer not to say",
    }
    return mapping.get(key, text)


def normalize_uk_mobile(value: Any, *, redacted_sample: bool = False) -> str | None:
    if value is None:
        return None

    # Excel may return phone numbers as numeric cells.
    # Avoid values such as 7712345678.0.
    if isinstance(value, float):
        if value.is_integer():
            text = str(int(value))
        else:
            text = str(value)
    elif isinstance(value, int):
        text = str(value)
    else:
        text = clean_text(value, redacted_sample=redacted_sample)

    if not text:
        return None

    # Remove normal phone formatting.
    compact = re.sub(r"[\s().\-]", "", text)

    # 07712345678
    if re.fullmatch(r"07\d{9}", compact):
        return "+44" + compact[1:]

    # Excel has removed the leading zero:
    # 7712345678
    if re.fullmatch(r"7\d{9}", compact):
        return "+44" + compact

    # +447712345678
    if re.fullmatch(r"\+447\d{9}", compact):
        return compact

    # 447712345678
    if re.fullmatch(r"447\d{9}", compact):
        return "+" + compact

    # 00447712345678
    if re.fullmatch(r"00447\d{9}", compact):
        return "+" + compact[2:]

    # Handles +44(0)7712345678
    if re.fullmatch(r"\+4407\d{9}", compact):
        return "+44" + compact[4:]

    return None


def normalize_email(value: Any, *, redacted_sample: bool = False) -> str | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None

    # Deliberately conservative. Bad emails are preserved as warnings rather than invented/fixed.
    if re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", text):
        return text

    return None


def normalize_postcode(value: str) -> str:
    compact = re.sub(r"\s+", "", value.upper())
    return compact[:-3] + " " + compact[-3:]


def extract_address_postcode(
    value: Any,
    *,
    redacted_sample: bool = False,
) -> tuple[str | None, str | None]:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None, None

    matches = list(UK_POSTCODE_RE.finditer(text))
    if not matches:
        return text, None

    match = matches[-1]
    postcode = normalize_postcode(match.group(1))
    address = (text[: match.start()] + " " + text[match.end() :]).strip(" ,;-")
    address = re.sub(r"\s+", " ", address).strip()
    return address or None, postcode


def parse_yes_no(value: Any, *, redacted_sample: bool = False) -> bool | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if text is None:
        return None

    key = text.casefold().strip()
    if key in YES_TEXT:
        return True
    if key in NO_TEXT:
        return False
    return None


def health_value(
    value: Any,
    *,
    redacted_sample: bool = False,
) -> tuple[bool | None, str | None]:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None, None

    key = text.casefold().strip()
    if key in NEGATIVE_TEXT:
        return False, None

    yes_no = parse_yes_no(text, redacted_sample=redacted_sample)
    if yes_no is False:
        return False, None
    if yes_no is True:
        # "Yes" with no details: keep flag true, details unavailable.
        return True, None

    return True, text


def parse_communication_preferences(
    value: Any,
    *,
    redacted_sample: bool = False,
) -> dict[str, bool] | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None

    lower = text.casefold()

    prefs = {
        "email": False,
        "sms": False,
        "phone": False,
        "whatsapp": False,
        "post": False,
        "do_not_contact": False,
    }

    if any(token in lower for token in ("do not contact", "no contact", "none")):
        prefs["do_not_contact"] = True
        return prefs

    prefs["email"] = "email" in lower
    prefs["sms"] = "text" in lower or "sms" in lower
    prefs["phone"] = "phone" in lower or "call" in lower
    prefs["whatsapp"] = "whatsapp" in lower
    prefs["post"] = bool(re.search(r"\bpost\b", lower))

    return prefs


def parse_gdpr(value: Any, *, redacted_sample: bool = False) -> tuple[bool | None, bool | None]:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None, None

    lower = text.casefold()

    if lower in NO_TEXT:
        return False, False

    gdpr = None
    anon = None

    if "processing of my personal data" in lower or "process my personal data" in lower:
        gdpr = True

    if "anonymised data" in lower or "anonymized data" in lower:
        anon = True

    return gdpr, anon


def meaningful_safeguarding_concern(value: Any, *, redacted_sample: bool = False) -> str | None:
    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None

    if text.casefold() in NEGATIVE_TEXT:
        return None

    parsed = parse_yes_no(text, redacted_sample=redacted_sample)
    if parsed is False:
        return None

    return text


# ---------------------------------------------------------------------------
# EXCEL DATES
# ---------------------------------------------------------------------------

def parse_excel_date(
    value: Any,
    workbook_epoch: datetime,
    *,
    redacted_sample: bool = False,
) -> str | None:
    if value is None:
        return None

    if isinstance(value, datetime):
        return value.date().isoformat()

    if isinstance(value, date):
        return value.isoformat()

    if isinstance(value, (int, float)):
        # Excel serial date. Reasonable serial range avoids treating normal small integers as dates.
        if value < 1 or value > 100000:
            return None
        try:
            dt = from_excel(value, workbook_epoch)
            if isinstance(dt, datetime):
                return dt.date().isoformat()
            if isinstance(dt, date):
                return dt.isoformat()
        except Exception:
            return None

    text = clean_text(value, redacted_sample=redacted_sample)
    if not text:
        return None

    if " to " in text.casefold():
        return None

    for fmt in (
        "%Y-%m-%d",
        "%d/%m/%Y",
        "%d-%m-%Y",
        "%d.%m.%Y",
        "%m/%d/%Y",
        "%b %d, %Y",
        "%B %d, %Y",
    ):
        try:
            return datetime.strptime(text, fmt).date().isoformat()
        except ValueError:
            continue

    return None


def age_on(dob_iso: str, reference_iso: str | None) -> int:
    dob = date.fromisoformat(dob_iso)
    reference = date.fromisoformat(reference_iso) if reference_iso else date.today()
    years = reference.year - dob.year - ((reference.month, reference.day) < (dob.month, dob.day))
    return years


# ---------------------------------------------------------------------------
# WORKBOOK PARSING
# ---------------------------------------------------------------------------

class MondaySheet:
    def __init__(self, path: Path, redacted_sample: bool = False):
        self.path = path
        self.redacted_sample = redacted_sample
        self.workbook = load_workbook(path, data_only=True, read_only=True)
        self.sheet = self.workbook.active
        self.epoch = self.workbook.epoch
        self.header_row_index, self.headers = self._find_header_row()
        self.header_positions = self._header_positions()

    def _find_header_row(self) -> tuple[int, list[str]]:
        for row_index, row in enumerate(self.sheet.iter_rows(values_only=True), start=1):
            values = [clean_text(v) or "" for v in row]
            if "Name" in values and "Date of Birth" in values and "Gender" in values:
                return row_index, values
        raise RuntimeError(
            "Could not find the Monday.com header row. Expected at least Name, Gender and Date of Birth."
        )

    def _header_positions(self) -> dict[str, list[int]]:
        positions: dict[str, list[int]] = {}
        for index, header in enumerate(self.headers):
            header = header.strip()
            if not header:
                continue
            positions.setdefault(header, []).append(index)
        return positions

    def value(self, row: tuple[Any, ...], header: str, occurrence: int = 0) -> Any:
        indexes = self.header_positions.get(header, [])
        if occurrence >= len(indexes):
            return None
        idx = indexes[occurrence]
        return row[idx] if idx < len(row) else None

    def values(self, row: tuple[Any, ...], header: str) -> list[Any]:
        out = []
        for idx in self.header_positions.get(header, []):
            out.append(row[idx] if idx < len(row) else None)
        return out

    def participant_rows(self) -> Iterable[tuple[int, tuple[Any, ...]]]:
        for row_index, row in enumerate(self.sheet.iter_rows(values_only=True), start=1):
            if row_index <= self.header_row_index:
                continue

            name_raw = self.value(row, "Name")
            name = clean_text(name_raw)

            # Skip genuinely empty rows and the Monday summary/range row in the sample export.
            if not name:
                continue
            if name == SAMPLE_REDACTED_VALUE:
                continue

            dob_raw = self.value(row, "Date of Birth")
            dob_text = clean_text(dob_raw)
            if dob_text and " to " in dob_text.casefold():
                continue

            yield row_index, row


# ---------------------------------------------------------------------------
# DATABASE
# ---------------------------------------------------------------------------

def connect_mysql(connection_string: str) -> Connection:
    parsed = urlparse(connection_string)

    if parsed.scheme not in {"mysql", "mysql+pymysql"}:
        raise ValueError(
            "Connection string must start with mysql:// or mysql+pymysql://"
        )

    if not parsed.hostname or not parsed.username or not parsed.path.strip("/"):
        raise ValueError(
            "Connection string is incomplete. Expected mysql://USER:PASSWORD@HOST:3306/DATABASE"
        )

    query = parse_qs(parsed.query)
    charset = query.get("charset", ["utf8mb4"])[0]
    ssl_requested = query.get("ssl", ["false"])[0].casefold() in {"1", "true", "yes"}

    kwargs: dict[str, Any] = {
        "host": parsed.hostname,
        "port": parsed.port or 3306,
        "user": unquote(parsed.username),
        "password": unquote(parsed.password or ""),
        "database": parsed.path.lstrip("/"),
        "charset": charset,
        "autocommit": False,
        "cursorclass": pymysql.cursors.DictCursor,
        "connect_timeout": 15,
        "read_timeout": 60,
        "write_timeout": 60,
    }

    if ssl_requested:
        kwargs["ssl"] = {}

    conn = pymysql.connect(**kwargs)
    with conn.cursor() as cur:
        cur.execute("SET time_zone = '+00:00'")
    return conn


def check_schema(conn: Connection) -> None:
    required_tables = {
        "participants",
        "participant_id_sequences",
        "participant_guardians",
        "emergency_contacts",
        "participant_health",
        "participant_equality",
        "communication_preferences",
        "consent_records",
        "audit_logs",
    }

    with conn.cursor() as cur:
        cur.execute("SHOW TABLES")
        found = {next(iter(row.values())) for row in cur.fetchall()}

    missing = sorted(required_tables - found)
    if missing:
        raise RuntimeError(
            "Database is missing required OCF CRM tables: " + ", ".join(missing)
        )


def current_next_participant_number(conn: Connection) -> int:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT next_number FROM participant_id_sequences "
            "WHERE sequence_name='participant' LIMIT 1"
        )
        row = cur.fetchone()
    if not row:
        raise RuntimeError("participant_id_sequences does not contain the participant sequence.")
    number = int(row["next_number"])
    if number < 1:
        raise RuntimeError("Participant sequence is invalid.")
    return number


def allocate_participant_number(conn: Connection) -> int:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT next_number FROM participant_id_sequences "
            "WHERE sequence_name=%s FOR UPDATE",
            ("participant",),
        )
        row = cur.fetchone()
        if not row:
            raise RuntimeError("Participant ID sequence is not configured.")

        number = int(row["next_number"])
        if number < 1:
            raise RuntimeError("Participant ID sequence is invalid.")

        cur.execute(
            "UPDATE participant_id_sequences "
            "SET next_number=next_number+1 "
            "WHERE sequence_name=%s AND next_number=%s",
            ("participant", number),
        )
        if cur.rowcount != 1:
            raise RuntimeError("Participant ID sequence could not be advanced.")

    return number


def ocf_id(first_name: str, last_name: str, participant_number: int) -> str:
    first_initial = first_name.strip()[0].upper()
    last_initial = last_name.strip()[0].upper()

    if not first_initial.isalpha() or not last_initial.isalpha():
        raise ValueError("First and last names must each begin with a letter.")

    return f"OCF-{first_initial}{last_initial}-{participant_number:04d}"


def find_duplicates(
    conn: Connection,
    full_name: str,
    dob: str,
    mobile: str | None,
    guardian_phone: str | None,
) -> list[dict[str, Any]]:
    matches: dict[str, dict[str, Any]] = {}

    def add(rows: list[dict[str, Any]], matched_by: str) -> None:
        for row in rows:
            pid = str(row["id"])
            entry = matches.setdefault(
                pid,
                {
                    "id": pid,
                    "ocfId": row["ocf_id"],
                    "fullName": row["full_name"],
                    "dateOfBirth": str(row["date_of_birth"]),
                    "mobileNumber": row["mobile_number"],
                    "matchedBy": [],
                },
            )
            if matched_by not in entry["matchedBy"]:
                entry["matchedBy"].append(matched_by)

    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id,ocf_id,full_name,date_of_birth,mobile_number
            FROM participants
            WHERE LOWER(TRIM(full_name)) = LOWER(TRIM(%s))
              AND date_of_birth = %s
            LIMIT 20
            """,
            (full_name, dob),
        )
        add(cur.fetchall(), "name+dob")

        if mobile:
            cur.execute(
                """
                SELECT id,ocf_id,full_name,date_of_birth,mobile_number
                FROM participants
                WHERE mobile_number = %s
                  AND date_of_birth = %s
                LIMIT 20
                """,
                (mobile, dob),
            )
            add(cur.fetchall(), "mobile+dob")

        if guardian_phone:
            cur.execute(
                """
                SELECT DISTINCT p.id,p.ocf_id,p.full_name,p.date_of_birth,p.mobile_number
                FROM participants p
                INNER JOIN participant_guardians g ON g.participant_id=p.id
                WHERE g.phone_number=%s
                  AND p.date_of_birth=%s
                LIMIT 20
                """,
                (guardian_phone, dob),
            )
            add(cur.fetchall(), "guardian_phone+dob")

    return list(matches.values())


# ---------------------------------------------------------------------------
# ROW MAPPING
# ---------------------------------------------------------------------------

def choose_photo_consent(
    values: list[Any],
    *,
    redacted_sample: bool = False,
) -> tuple[bool | None, str | None]:
    parsed: list[bool] = []
    for value in values:
        answer = parse_yes_no(value, redacted_sample=redacted_sample)
        if answer is not None:
            parsed.append(answer)

    if not parsed:
        return None, None

    if len(set(parsed)) > 1:
        return None, "Conflicting Photo/Video Consent values in duplicated Monday columns."

    return parsed[0], None


def prepare_row(
    sheet: MondaySheet,
    source_row: int,
    row: tuple[Any, ...],
    batch: str,
    allow_guardian_phone_for_adults: bool,
) -> PreparedParticipant:
    redacted = sheet.redacted_sample
    out = PreparedParticipant(source_row=source_row, batch=batch)

    out.full_name = normalize_name(
        sheet.value(row, "Name"),
        redacted_sample=redacted,
    ) or ""

    if not out.full_name:
        out.blockers.append("Missing participant name.")
    else:
        first, last = split_participant_name(out.full_name)
        if not first or not last:
            out.blockers.append(
                "Cannot safely split participant name into first name + last name; OCF ID requires both."
            )
        else:
            out.first_name = first
            out.last_name = last

    out.date_of_birth = parse_excel_date(
        sheet.value(row, "Date of Birth"),
        sheet.epoch,
        redacted_sample=redacted,
    )
    if not out.date_of_birth:
        out.blockers.append("Missing or invalid Date of Birth.")

    out.date_form_completed = parse_excel_date(
        sheet.value(row, "Date Form Completed"),
        sheet.epoch,
        redacted_sample=redacted,
    )
    if not out.date_form_completed:
        out.warnings.append("Date Form Completed is missing/invalid; migration date will be used for created_at.")

    if out.date_of_birth:
        try:
            out.age_at_form = age_on(out.date_of_birth, out.date_form_completed)
        except Exception:
            out.age_at_form = None

    out.gender = normalize_gender(
        sheet.value(row, "Gender"),
        redacted_sample=redacted,
    )

    if batch.casefold() == "girls" and out.gender == "Male":
        out.warnings.append("Row is in Girls batch but source Gender is Male.")
    if batch.casefold() == "boys" and out.gender == "Female":
        out.warnings.append("Row is in Boys batch but source Gender is Female.")

    out.source_status = clean_text(
        sheet.value(row, "Status"),
        redacted_sample=redacted,
    )
    out.school_name = clean_text(
        sheet.value(row, "School Name"),
        redacted_sample=redacted,
    )

    out.home_address, out.postcode = extract_address_postcode(
        sheet.value(row, "Home Address and Postcode"),
        redacted_sample=redacted,
    )
    if not out.postcode:
        out.blockers.append("Could not extract a valid UK postcode from Home Address and Postcode.")

    out.guardian_name = normalize_name(
        sheet.value(row, "Parent/Guardian Name"),
        redacted_sample=redacted,
    )
    raw_guardian_phone = sheet.value(row, "Parent/Guardian Phone Number")
    out.guardian_phone = normalize_uk_mobile(
        raw_guardian_phone,
        redacted_sample=redacted,
    )
    guardian_phone_text = clean_text(raw_guardian_phone, redacted_sample=redacted)
    if guardian_phone_text and not out.guardian_phone:
        out.warnings.append("Parent/Guardian Phone Number is present but is not a valid UK mobile.")

    raw_guardian_email = sheet.value(row, "Parent/Guardian Email Address")
    out.guardian_email = normalize_email(
        raw_guardian_email,
        redacted_sample=redacted,
    )
    guardian_email_text = clean_text(raw_guardian_email, redacted_sample=redacted)
    if guardian_email_text and not out.guardian_email:
        out.warnings.append("Parent/Guardian Email Address is present but invalid.")

    out.emergency_name = normalize_name(
        sheet.value(row, "Emergency Contact Name"),
        redacted_sample=redacted,
    )
    out.emergency_relationship = clean_text(
        sheet.value(row, "Relationship to the Participant"),
        redacted_sample=redacted,
    )
    raw_emergency_phone = sheet.value(row, "Emergency Contact Phone Number")
    out.emergency_phone = normalize_uk_mobile(
        raw_emergency_phone,
        redacted_sample=redacted,
    )
    emergency_phone_text = clean_text(raw_emergency_phone, redacted_sample=redacted)
    if emergency_phone_text and not out.emergency_phone:
        out.warnings.append("Emergency Contact Phone Number is present but is not a valid UK mobile.")

    out.emergency_pickup_authorised = parse_yes_no(
        sheet.value(row, "Is this person authorised to pick up the participant?"),
        redacted_sample=redacted,
    )

    # Monday source has no participant mobile column.
    # Safe fallback: primary guardian mobile for under-18.
    if out.age_at_form is not None and out.age_at_form < 18:
        out.guardian_relationship = "Parent/Guardian"
        if not out.guardian_name:
            out.blockers.append("Under-18 participant has no Parent/Guardian Name.")
        if not out.guardian_phone:
            out.blockers.append("Under-18 participant has no valid Parent/Guardian mobile.")
        if out.guardian_phone:
            out.mobile_number = out.guardian_phone
            out.mobile_source = "guardian"
    else:
        if allow_guardian_phone_for_adults and out.guardian_phone:
            out.mobile_number = out.guardian_phone
            out.mobile_source = "guardian_adult_override"
            out.warnings.append(
                "Adult/unknown-age participant mobile populated from guardian phone because override was enabled."
            )
        else:
            out.blockers.append(
                "No participant mobile exists in Monday export. For age 18+ / unknown age, manual review is required."
            )

    # Emergency contact safety rule.
    emergency_complete = bool(
        out.emergency_name
        and out.emergency_relationship
        and out.emergency_phone
    )
    if out.age_at_form is not None and out.age_at_form < 18:
        if not emergency_complete:
            out.blockers.append(
                "Under-18 participant does not have a complete emergency contact (name, relationship, valid mobile)."
            )
    elif any((out.emergency_name, out.emergency_relationship, out.emergency_phone)) and not emergency_complete:
        out.warnings.append("Emergency contact is incomplete and will not be inserted.")

    # Health.
    has_medical, medical = health_value(
        sheet.value(row, "Medical Condition"),
        redacted_sample=redacted,
    )
    has_dietary, dietary = health_value(
        sheet.value(row, "Dietary Needs/Allergies"),
        redacted_sample=redacted,
    )
    takes_medication, medication = health_value(
        sheet.value(row, "Are you currently taking any medication?"),
        redacted_sample=redacted,
    )
    has_disability, disability = health_value(
        sheet.value(row, "Disability"),
        redacted_sample=redacted,
    )
    gp_details = clean_text(
        sheet.value(row, "Doctor’s Name and Contact Number (GP):"),
        redacted_sample=redacted,
    )

    out.health = {
        "has_medical_condition": has_medical,
        "medical_condition": medical,
        "has_dietary_needs_allergies": has_dietary,
        "dietary_needs_allergies": dietary,
        "takes_medication": takes_medication,
        "medication": medication,
        "has_disability": has_disability,
        "disability": disability,
        "gp_details": gp_details,
    }

    out.ethnic_origin = clean_text(
        sheet.value(row, "Ethnic Origin"),
        redacted_sample=redacted,
    )
    out.religion = clean_text(
        sheet.value(row, "Religion"),
        redacted_sample=redacted,
    )

    out.communication = parse_communication_preferences(
        sheet.value(row, "Consent for Communication:"),
        redacted_sample=redacted,
    )

    out.photo_video_consent, photo_error = choose_photo_consent(
        sheet.values(row, "Photo/Video Consent"),
        redacted_sample=redacted,
    )
    if photo_error:
        out.blockers.append(photo_error)

    out.gdpr_personal_data_consent, out.anonymised_reporting_consent = parse_gdpr(
        sheet.value(row, "GDPR and Data Protection"),
        redacted_sample=redacted,
    )

    safeguarding = meaningful_safeguarding_concern(
        sheet.value(row, "Safeguarding Concerns"),
        redacted_sample=redacted,
    )
    if safeguarding:
        out.blockers.append(
            "Safeguarding Concerns contains meaningful data but current OCF schema has no safe mapped destination. Review manually before migration."
        )

    out.signature_url = clean_text(
        sheet.value(row, "Signature"),
        redacted_sample=redacted,
    )
    if out.signature_url:
        out.warnings.append(
            "Legacy signature URL found. It will NOT be inserted into signatures because OCF signatures require a private stored file + hash."
        )

    out.consent_form_value = clean_text(
        sheet.value(row, "Consent Form"),
        redacted_sample=redacted,
    )
    if out.consent_form_value:
        out.warnings.append("Consent Form source value/file is not mapped; retained in local migration audit only.")

    out.notes_value = clean_text(
        sheet.value(row, "Notes"),
        redacted_sample=redacted,
    )
    if out.notes_value:
        out.warnings.append("Monday Notes are not mapped to a current participant column; retained in local migration audit only.")

    out.files_value = clean_text(
        sheet.value(row, "Files"),
        redacted_sample=redacted,
    )
    if out.files_value:
        out.warnings.append("Monday Files are not mapped to a current participant column; retained in local migration audit only.")

    # Do NOT map Monday Status to registration_status.
    if out.source_status:
        out.warnings.append(
            f"Monday Status '{out.source_status}' preserved only as migration metadata; not mapped to OCF registration_status."
        )

    return out


# ---------------------------------------------------------------------------
# INSERTS
# ---------------------------------------------------------------------------

def insert_consent(
    conn: Connection,
    participant_id: str,
    consent_type: str,
    granted: bool | None,
    given_by: str | None,
    given_at: str | None,
) -> None:
    if granted is None:
        return

    status = "Granted" if granted else "Declined"
    given_datetime = (
        datetime.combine(date.fromisoformat(given_at), time(hour=12))
        if given_at
        else datetime.utcnow()
    )

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO consent_records
            (id,participant_id,consent_type,status,given_by_name,given_at,wording_version,metadata_json)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
            """,
            (
                str(uuid.uuid4()),
                participant_id,
                consent_type,
                status,
                given_by,
                given_datetime,
                "LEGACY_MONDAY_EXPORT",
                json.dumps({"migration": MIGRATION_NAME}),
            ),
        )


def insert_participant(
    conn: Connection,
    p: PreparedParticipant,
) -> tuple[str, str]:
    if not p.ready:
        raise RuntimeError("Attempted to insert a participant that is not ready.")

    participant_id = str(uuid.uuid4())
    participant_number = allocate_participant_number(conn)
    generated_ocf_id = ocf_id(p.first_name, p.last_name, participant_number)

    historical_created_at = (
        datetime.combine(date.fromisoformat(p.date_form_completed), time(hour=12))
        if p.date_form_completed
        else datetime.utcnow()
    )

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO participants
            (
                id,participant_number,ocf_id,
                registration_type,registration_status,registration_source,
                first_name,last_name,full_name,date_of_birth,
                mobile_number,email_address,postcode,gender,school_name,home_address,
                can_walk_home,date_form_completed,created_by,updated_by,
                created_at,updated_at
            )
            VALUES
            (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,NULL,%s,%s,%s,%s,NULL,%s,NULL,NULL,%s,NOW())
            """,
            (
                participant_id,
                participant_number,
                generated_ocf_id,
                REGISTRATION_TYPE,
                REGISTRATION_STATUS,
                REGISTRATION_SOURCE,
                p.first_name,
                p.last_name,
                p.full_name,
                p.date_of_birth,
                p.mobile_number,
                p.postcode,
                p.gender,
                p.school_name,
                p.home_address,
                p.date_form_completed,
                historical_created_at,
            ),
        )

        guardian_id: str | None = None
        if p.guardian_name and p.guardian_phone:
            guardian_id = str(uuid.uuid4())
            cur.execute(
                """
                INSERT INTO participant_guardians
                (id,participant_id,full_name,relationship,phone_number,email_address,is_primary)
                VALUES (%s,%s,%s,%s,%s,%s,1)
                """,
                (
                    guardian_id,
                    participant_id,
                    p.guardian_name,
                    p.guardian_relationship,
                    p.guardian_phone,
                    p.guardian_email,
                ),
            )

        if p.emergency_name and p.emergency_relationship and p.emergency_phone:
            linked_guardian_id = None
            if (
                guardian_id
                and p.guardian_name
                and p.emergency_name.casefold().strip() == p.guardian_name.casefold().strip()
            ):
                linked_guardian_id = guardian_id

            cur.execute(
                """
                INSERT INTO emergency_contacts
                (id,participant_id,full_name,relationship,phone_number,is_pickup_authorised,linked_guardian_id)
                VALUES (%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    str(uuid.uuid4()),
                    participant_id,
                    p.emergency_name,
                    p.emergency_relationship,
                    p.emergency_phone,
                    1 if p.emergency_pickup_authorised else 0,
                    linked_guardian_id,
                ),
            )

        if any(v is not None for v in p.health.values()):
            cur.execute(
                """
                INSERT INTO participant_health
                (
                    participant_id,
                    has_medical_condition,medical_condition,
                    has_dietary_needs_allergies,dietary_needs_allergies,
                    takes_medication,medication,
                    has_disability,disability,
                    gp_details
                )
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    participant_id,
                    p.health.get("has_medical_condition"),
                    p.health.get("medical_condition"),
                    p.health.get("has_dietary_needs_allergies"),
                    p.health.get("dietary_needs_allergies"),
                    p.health.get("takes_medication"),
                    p.health.get("medication"),
                    p.health.get("has_disability"),
                    p.health.get("disability"),
                    p.health.get("gp_details"),
                ),
            )

        if p.ethnic_origin is not None or p.religion is not None:
            cur.execute(
                """
                INSERT INTO participant_equality
                (participant_id,ethnic_origin,religion)
                VALUES (%s,%s,%s)
                """,
                (participant_id, p.ethnic_origin, p.religion),
            )

        if p.communication is not None:
            cur.execute(
                """
                INSERT INTO communication_preferences
                (participant_id,email,sms,phone,whatsapp,post,do_not_contact)
                VALUES (%s,%s,%s,%s,%s,%s,%s)
                """,
                (
                    participant_id,
                    int(p.communication["email"]),
                    int(p.communication["sms"]),
                    int(p.communication["phone"]),
                    int(p.communication["whatsapp"]),
                    int(p.communication["post"]),
                    int(p.communication["do_not_contact"]),
                ),
            )

    consent_given_by = p.guardian_name if (p.age_at_form is not None and p.age_at_form < 18) else p.full_name

    insert_consent(
        conn,
        participant_id,
        "PhotoVideo",
        p.photo_video_consent,
        consent_given_by,
        p.date_form_completed,
    )
    insert_consent(
        conn,
        participant_id,
        "GdprPersonalData",
        p.gdpr_personal_data_consent,
        consent_given_by,
        p.date_form_completed,
    )
    insert_consent(
        conn,
        participant_id,
        "AnonymisedReporting",
        p.anonymised_reporting_consent,
        consent_given_by,
        p.date_form_completed,
    )

    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO audit_logs
            (user_id,participant_id,action,entity_type,entity_id,ip_address,user_agent,metadata_json)
            VALUES (NULL,%s,%s,'Participant',%s,NULL,%s,%s)
            """,
            (
                participant_id,
                AUDIT_ACTION,
                participant_id,
                "python-monday-migration",
                json.dumps(
                    {
                        "migration": MIGRATION_NAME,
                        "batch": p.batch,
                        "sourceRow": p.source_row,
                        "sourceStatus": p.source_status,
                        "mobileSource": p.mobile_source,
                        "legacySignatureUrlPresent": bool(p.signature_url),
                        "warnings": p.warnings,
                    },
                    ensure_ascii=False,
                ),
            ),
        )

    return participant_id, generated_ocf_id


# ---------------------------------------------------------------------------
# REPORTING
# ---------------------------------------------------------------------------

def audit_row(p: PreparedParticipant) -> dict[str, Any]:
    if p.duplicate_matches:
        result = "DUPLICATE_REVIEW"
    elif p.blockers:
        result = "BLOCKED_REVIEW"
    elif p.inserted_ocf_id:
        result = "INSERTED"
    else:
        result = "READY"

    duplicate_text = "; ".join(
        f"{m['ocfId']} ({','.join(m['matchedBy'])})"
        for m in p.duplicate_matches
    )

    return {
        "source_row": p.source_row,
        "batch": p.batch,
        "result": result,
        "full_name": p.full_name,
        "date_of_birth": p.date_of_birth or "",
        "age_at_form": p.age_at_form if p.age_at_form is not None else "",
        "gender": p.gender or "",
        "postcode": p.postcode or "",
        "mobile_source": p.mobile_source or "",
        "preview_ocf_id": p.preview_ocf_id or "",
        "inserted_ocf_id": p.inserted_ocf_id or "",
        "duplicate_matches": duplicate_text,
        "blockers": " | ".join(p.blockers),
        "warnings": " | ".join(p.warnings),
        "monday_status": p.source_status or "",
        "legacy_signature_url": p.signature_url or "",
        "unmapped_notes": p.notes_value or "",
        "unmapped_files": p.files_value or "",
        "consent_form_source": p.consent_form_value or "",
    }


def write_audit_csv(path: Path, rows: list[PreparedParticipant]) -> None:
    fieldnames = list(audit_row(rows[0]).keys()) if rows else [
        "source_row",
        "batch",
        "result",
    ]

    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for p in rows:
            writer.writerow(audit_row(p))


def summary_counts(rows: list[PreparedParticipant]) -> dict[str, int]:
    return {
        "source_rows": len(rows),
        "ready_or_inserted": sum(1 for p in rows if p.ready),
        "duplicates_review": sum(1 for p in rows if p.duplicate_matches),
        "blocked_review": sum(1 for p in rows if p.blockers and not p.duplicate_matches),
        "with_warnings": sum(1 for p in rows if p.warnings),
        "inserted": sum(1 for p in rows if p.inserted_ocf_id),
    }


def print_summary(
    source: Path,
    batch: str,
    rows: list[PreparedParticipant],
    audit_path: Path,
    committed: bool,
) -> None:
    counts = summary_counts(rows)

    print()
    print("OCF Monday Participant Migration")
    print("--------------------------------")
    print(f"Source:                         {source}")
    print(f"Batch:                          {batch}")
    print(f"Source participant rows:        {counts['source_rows']}")
    print(f"Ready / eligible:               {counts['ready_or_inserted']}")
    print(f"Possible duplicates (REVIEW):   {counts['duplicates_review']}")
    print(f"Blocked rows (REVIEW):          {counts['blocked_review']}")
    print(f"Rows with warnings:             {counts['with_warnings']}")
    if committed:
        print(f"Inserted:                       {counts['inserted']}")
    print(f"Audit CSV:                      {audit_path}")
    print()

    if committed:
        print("COMMIT COMPLETE: eligible participants were inserted.")
    else:
        print("PREVIEW COMPLETE: database was NOT changed.")
        print("Review the audit CSV, then rerun with --commit only when you are satisfied.")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Migrate Monday.com OCF participant Excel export into OCF CRM MySQL."
    )
    parser.add_argument(
        "--source",
        required=True,
        help="Path to Monday.com participant export .xlsx",
    )
    parser.add_argument(
        "--batch",
        required=True,
        choices=["girls", "boys", "mixed"],
        help="Source batch label only. It does NOT create separate CRM structures.",
    )
    parser.add_argument(
        "--connection-string",
        default=DEFAULT_CONNECTION_STRING,
        help=(
            "MySQL URL. Prefer OCF_MYSQL_CONNECTION_STRING environment variable. "
            "Example: mysql://user:password@host:3306/ocf_crm?charset=utf8mb4"
        ),
    )
    parser.add_argument(
        "--commit",
        action="store_true",
        help="Actually write READY rows. Without this flag the script is preview-only.",
    )
    parser.add_argument(
        "--allow-guardian-phone-for-adults",
        action="store_true",
        default=ALLOW_GUARDIAN_PHONE_FOR_18_PLUS_DEFAULT,
        help=(
            "Override: permit guardian mobile to populate participants.mobile_number "
            "for age 18+ / unknown age. Default is OFF."
        ),
    )
    parser.add_argument(
        "--redacted-sample",
        action="store_true",
        help=(
            "Use ONLY with the sample workbook where exact value '34' is a redaction placeholder. "
            "Do NOT use for the real export."
        ),
    )
    return parser.parse_args()


def validate_connection_string(value: str) -> None:
    if "YOUR_DB_" in value:
        raise RuntimeError(
            "Replace the placeholder connection string or set OCF_MYSQL_CONNECTION_STRING."
        )


def main() -> int:
    args = parse_args()

    source = Path(args.source).expanduser().resolve()
    if not source.exists():
        print(f"ERROR: Source file not found: {source}", file=sys.stderr)
        return 2

    if source.suffix.casefold() != ".xlsx":
        print("ERROR: Source must be an .xlsx file.", file=sys.stderr)
        return 2

    try:
        validate_connection_string(args.connection_string)
        conn = connect_mysql(args.connection_string)
    except Exception as exc:
        print(f"ERROR connecting to MySQL: {exc}", file=sys.stderr)
        return 3

    try:
        check_schema(conn)

        monday = MondaySheet(source, redacted_sample=args.redacted_sample)
        prepared: list[PreparedParticipant] = []

        for source_row, row in monday.participant_rows():
            p = prepare_row(
                monday,
                source_row,
                row,
                args.batch,
                args.allow_guardian_phone_for_adults,
            )
            prepared.append(p)

        # Duplicate checks happen even in PREVIEW.
        for p in prepared:
            if p.date_of_birth and p.full_name:
                p.duplicate_matches = find_duplicates(
                    conn,
                    p.full_name,
                    p.date_of_birth,
                    p.mobile_number,
                    p.guardian_phone,
                )

        # Preview OCF IDs are simulated from the current sequence.
        simulated_next = current_next_participant_number(conn)
        for p in prepared:
            if p.ready and p.first_name and p.last_name:
                try:
                    p.preview_ocf_id = ocf_id(
                        p.first_name,
                        p.last_name,
                        simulated_next,
                    )
                    simulated_next += 1
                except Exception as exc:
                    p.blockers.append(f"Could not generate OCF ID: {exc}")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        mode = "commit" if args.commit else "preview"
        audit_path = source.parent / (
            f"ocf_monday_{args.batch}_{mode}_{timestamp}.csv"
        )

        if args.commit:
            # Recheck everything inside one transaction.
            # Any unexpected DB exception rolls back the whole inserted batch.
            conn.begin()
            try:
                for p in prepared:
                    if p.blockers:
                        continue

                    p.duplicate_matches = find_duplicates(
                        conn,
                        p.full_name,
                        p.date_of_birth or "",
                        p.mobile_number,
                        p.guardian_phone,
                    )
                    if p.duplicate_matches:
                        continue

                    participant_id, generated_ocf_id = insert_participant(conn, p)
                    p.inserted_participant_id = participant_id
                    p.inserted_ocf_id = generated_ocf_id

                conn.commit()
            except Exception:
                conn.rollback()
                raise
        else:
            # Ensure preview remains read-only even if driver started a transaction.
            conn.rollback()

        write_audit_csv(audit_path, prepared)
        print_summary(source, args.batch, prepared, audit_path, args.commit)

        # Exit nonzero when review items exist, but only after producing the audit file.
        # This is useful in scripted runs and does not mean the script crashed.
        if any(p.blockers or p.duplicate_matches for p in prepared):
            return 10

        return 0

    except Exception as exc:
        try:
            conn.rollback()
        except Exception:
            pass
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
