#!/usr/bin/env python3
"""
OCF CRM - Historical Monday Sessions + Attendance Migration (Phase 2)

PHASE 2 ONLY
------------
Creates/reuses:
  - sessions
  - session_registrations
  - attendance

It DOES NOT create/update:
  - participants
  - participant_activity_types
  - activity_types
  - activities

Those were handled in Phase 1.

SAFETY
------
- Preview is the default.
- Database writes happen only with --commit.
- Participant identity comes only from the prior preview CSV where
  match_status == MATCHED_NAME_DOB.
- Blank Monday cells create no registration/attendance.
- Yes -> Attended + Present
- No  -> NoShow + Absent
- Explicit Cancelled source columns -> Cancelled session, no attendance.
- Duplicate source session dates for the SAME canonical activity are deduplicated
  only when their matched attendance sets agree.
- Conflicting duplicate source dates are blocked for manual review.
- Existing CRM sessions on the same canonical activity/date are reused only when
  the exact start/end time matches. A different existing time on the same date
  is treated as a conflict.
- Missing historical session times block commit; times are never invented.

REQUIRED INPUTS
---------------
1) Folder containing the original 30 attendance Excel files.
2) Participant preview CSV generated by:
     preview_ocf_monday_activity_sessions.py
3) Session preview CSV generated by:
     preview_ocf_monday_activity_sessions.py
4) A JSON time configuration file.

TIME CONFIG
-----------
The time JSON uses programme + weekday rules. Example:

{
  "Girls Football": {
    "Tuesday": {"start": "17:00", "end": "18:00"},
    "Wednesday": {"start": "17:00", "end": "18:00"}
  }
}

Optional date-range overrides are supported:

{
  "Girls Football": {
    "default": {"start": "17:00", "end": "18:00"},
    "overrides": [
      {
        "from": "2026-01-01",
        "to": "2026-12-31",
        "weekday": "Wednesday",
        "start": "18:00",
        "end": "19:00"
      }
    ]
  }
}

Resolution order:
  1. matching date-range override
  2. exact weekday rule
  3. default rule

RUN PREVIEW
-----------
py -3.14 .\migrate_ocf_sessions_attendance.py `
  --source-dir ".\Session Excels" `
  --participants-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_participants.csv" `
  --sessions-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_sessions.csv" `
  --times ".\ocf_session_times.json"

RUN COMMIT
----------
Only after preview has 0 blocking session/time conflicts:

py -3.14 .\migrate_ocf_sessions_attendance.py `
  --source-dir ".\Session Excels" `
  --participants-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_participants.csv" `
  --sessions-csv ".\ocf_monday_activity_sessions_preview_20260913_213900_sessions.csv" `
  --times ".\ocf_session_times.json" `
  --commit
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import unicodedata
import uuid
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from datetime import date, datetime, time
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, unquote, urlparse

import pymysql
from openpyxl import load_workbook

DEFAULT_CONNECTION_STRING = os.getenv(
    "OCF_MYSQL_CONNECTION_STRING",
    "mysql://YOUR_DB_USER:YOUR_DB_PASSWORD@YOUR_DB_HOST:3306/YOUR_DB_NAME?charset=utf8mb4",
)

MIGRATION_NAME = "OCF_MONDAY_SESSIONS_ATTENDANCE_V1"

CANONICAL_ACTIVITY = {
    "Girls Cricket": "Girl's Cricket",
    "Girls Football": "Girls Football",
    "Boys Football": "Boys Football",
    "Girls Youth Club": "Girls Youth Club",
    "Youth Club (Mixed)": "Youth Club (Mixed)",
    "HAF": "HAF",
    "XLR8": "XLR8",
}

YES_VALUES = {"yes", "y", "present", "attended", "1"}
NO_VALUES = {"no", "n", "absent", "0"}

# These are source programmes that can have historical sessions.
SESSION_PROGRAMMES = set(CANONICAL_ACTIVITY.keys())


@dataclass
class SourceMark:
    participant_id: str
    ocf_id: str
    participant_name: str
    value: str  # yes/no


@dataclass
class SourceSession:
    source_programme: str
    canonical_activity: str
    session_date: str
    source_file: str
    source_header: str
    source_status: str
    cancelled: bool
    marks: dict[str, SourceMark] = field(default_factory=dict)


@dataclass
class MergedSession:
    source_programme: str
    canonical_activity: str
    session_date: str
    cancelled: bool
    source_files: list[str]
    source_headers: list[str]
    marks: dict[str, SourceMark]
    duplicate_count: int
    duplicate_status: str
    time_start: str | None = None
    time_end: str | None = None
    time_rule: str = ""
    plan_action: str = ""
    existing_session_id: str | None = None
    session_id: str | None = None
    blocking_reason: str = ""


def clean(v: Any) -> str:
    if v is None:
        return ""

    return re.sub(r"\s+", " ", str(v)).strip()


def norm(v: Any) -> str:
    text = clean(v)
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    return re.sub(r"\s+", " ", text.casefold()).strip()


def normalize_attendance(v: Any) -> str:
    key = norm(v)
    if not key:
        return "blank"
    if key in YES_VALUES:
        return "yes"
    if key in NO_VALUES:
        return "no"
    return "other"


def connect_mysql(connection_string: str):
    p = urlparse(connection_string)
    if p.scheme not in {"mysql", "mysql+pymysql"}:
        raise ValueError("Connection string must begin mysql://")
    if not p.hostname or not p.username or not p.path.strip("/"):
        raise ValueError("Connection string is incomplete.")

    q = parse_qs(p.query)
    kwargs = {
        "host": p.hostname,
        "port": p.port or 3306,
        "user": unquote(p.username),
        "password": unquote(p.password or ""),
        "database": p.path.lstrip("/"),
        "charset": q.get("charset", ["utf8mb4"])[0],
        "autocommit": False,
        "cursorclass": pymysql.cursors.DictCursor,
        "connect_timeout": 15,
        "read_timeout": 60,
        "write_timeout": 60,
    }
    if q.get("ssl", ["false"])[0].lower() in {"1", "true", "yes"}:
        kwargs["ssl"] = {}

    conn = pymysql.connect(**kwargs)
    with conn.cursor() as cur:
        cur.execute("SET time_zone = '+00:00'")
    return conn


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def load_times(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise RuntimeError("Time config must be a JSON object.")
    return data


def valid_hhmm(value: str) -> bool:
    try:
        datetime.strptime(value, "%H:%M")
        return True
    except Exception:
        return False


def resolve_time(config: dict[str, Any], programme: str, session_date: str):
    pcfg = config.get(programme)
    if not isinstance(pcfg, dict):
        return None, None, "NO_PROGRAMME_TIME_CONFIG"

    dt = datetime.strptime(session_date, "%Y-%m-%d").date()
    weekday = dt.strftime("%A")

    overrides = pcfg.get("overrides", [])
    if isinstance(overrides, list):
        for i, rule in enumerate(overrides):
            if not isinstance(rule, dict):
                continue
            start_date = rule.get("from")
            end_date = rule.get("to")
            rule_weekday = rule.get("weekday")

            try:
                start_ok = not start_date or dt >= datetime.strptime(start_date, "%Y-%m-%d").date()
                end_ok = not end_date or dt <= datetime.strptime(end_date, "%Y-%m-%d").date()
            except ValueError:
                continue

            weekday_ok = not rule_weekday or norm(rule_weekday) == norm(weekday)

            if start_ok and end_ok and weekday_ok:
                start = clean(rule.get("start"))
                end = clean(rule.get("end"))
                if valid_hhmm(start) and valid_hhmm(end):
                    return start, end, f"override[{i}]"

    weekday_rule = pcfg.get(weekday)
    if isinstance(weekday_rule, dict):
        start = clean(weekday_rule.get("start"))
        end = clean(weekday_rule.get("end"))
        if valid_hhmm(start) and valid_hhmm(end):
            return start, end, f"weekday:{weekday}"

    default_rule = pcfg.get("default")
    if isinstance(default_rule, dict):
        start = clean(default_rule.get("start"))
        end = clean(default_rule.get("end"))
        if valid_hhmm(start) and valid_hhmm(end):
            return start, end, "default"

    return None, None, f"MISSING_TIME_FOR_{weekday.upper()}"


def load_participant_match_index(rows: list[dict[str, str]]):
    """
    Key by (file, source_row) because this is the exact row identity in the Excel export.
    """
    index = {}
    duplicates = []
    for row in rows:
        key = (clean(row.get("file")), clean(row.get("source_row")))
        if not all(key):
            continue
        if key in index:
            duplicates.append(key)
        index[key] = row
    if duplicates:
        raise RuntimeError(f"Duplicate participant preview row keys found: {duplicates[:5]}")
    return index


def load_source_session_index(session_rows: list[dict[str, str]]):
    """
    Key by (file, source_header) because each workbook header identifies a dated column.
    """
    index = {}
    duplicates = []
    for row in session_rows:
        key = (clean(row.get("file")), clean(row.get("source_header")))
        if not all(key):
            continue
        if key in index:
            duplicates.append(key)
        index[key] = row
    if duplicates:
        raise RuntimeError(f"Duplicate session preview row keys found: {duplicates[:5]}")
    return index


def find_header_row(ws):
    for row_no, row in enumerate(ws.iter_rows(values_only=True), start=1):
        vals = list(row)
        normalized = {norm(v) for v in vals if v is not None}
        if "date of birth" in normalized and (
            "participant list" in normalized or "girls participant list" in normalized
        ):
            return row_no, vals
        if row_no >= 10:
            break
    raise RuntimeError(f"Could not locate participant/date header row in sheet {ws.title!r}")


def build_excel_marks(
    source_dir: Path,
    participant_index,
    source_session_index,
):
    sessions: list[SourceSession] = []
    workbook_errors = []

    files = sorted(source_dir.glob("*.xlsx"))

    for path in files:
        filename = path.name

        session_rows_for_file = {
            header: row
            for (file_name, header), row in source_session_index.items()
            if file_name == filename
        }
        if not session_rows_for_file:
            # Not one of the configured/parsed attendance files.
            continue

        try:
            wb = load_workbook(path, data_only=True, read_only=True)
            ws = wb.active
            header_row_no, headers = find_header_row(ws)

            header_positions = {}
            for idx, h in enumerate(headers):
                header = clean(h)
                if header:
                    header_positions.setdefault(header, []).append(idx)

            # Build participant rows exactly from the prior preview row identity.
            participant_rows = {}
            for row_no, values in enumerate(ws.iter_rows(values_only=True), start=1):
                if row_no <= header_row_no:
                    continue
                preview = participant_index.get((filename, str(row_no)))
                if not preview:
                    continue

                participant_rows[row_no] = {
                    "values": list(values),
                    "preview": preview,
                }

            for source_header, srow in session_rows_for_file.items():
                source_programme = clean(srow.get("source_programme"))
                if source_programme not in SESSION_PROGRAMMES:
                    continue

                status = clean(srow.get("status"))
                session_date = clean(srow.get("session_date"))
                if not session_date:
                    continue

                cancelled = clean(srow.get("cancelled")).upper() == "YES"

                # Skip blank/unconfirmed source dates entirely.
                if "REVIEW_UNCONFIRMED_EMPTY_SESSION" in status and not cancelled:
                    continue

                positions = header_positions.get(source_header, [])
                if len(positions) != 1:
                    workbook_errors.append({
                        "file": filename,
                        "source_header": source_header,
                        "error": f"Expected exactly one matching header; found {len(positions)}",
                    })
                    continue

                col = positions[0]
                marks: dict[str, SourceMark] = {}

                if not cancelled:
                    for row_no, item in participant_rows.items():
                        preview = item["preview"]

                        if clean(preview.get("match_status")) != "MATCHED_NAME_DOB":
                            continue

                        participant_id = clean(preview.get("matched_participant_id"))
                        if not participant_id:
                            continue

                        values = item["values"]
                        value = values[col] if col < len(values) else None
                        mark = normalize_attendance(value)

                        if mark not in {"yes", "no"}:
                            continue

                        marks[participant_id] = SourceMark(
                            participant_id=participant_id,
                            ocf_id=clean(preview.get("matched_ocf_id")),
                            participant_name=clean(preview.get("matched_name")),
                            value=mark,
                        )

                sessions.append(
                    SourceSession(
                        source_programme=source_programme,
                        canonical_activity=CANONICAL_ACTIVITY[source_programme],
                        session_date=session_date,
                        source_file=filename,
                        source_header=source_header,
                        source_status=status,
                        cancelled=cancelled,
                        marks=marks,
                    )
                )

        except Exception as exc:
            workbook_errors.append({
                "file": filename,
                "source_header": "",
                "error": str(exc),
            })

    return sessions, workbook_errors


def merge_duplicate_source_sessions(source_sessions: list[SourceSession]):
    groups = defaultdict(list)
    for s in source_sessions:
        key = (s.canonical_activity, s.session_date)
        groups[key].append(s)

    merged: list[MergedSession] = []

    for (activity, session_date), rows in sorted(groups.items()):
        programme_set = {r.source_programme for r in rows}
        if len(programme_set) != 1:
            merged.append(
                MergedSession(
                    source_programme="; ".join(sorted(programme_set)),
                    canonical_activity=activity,
                    session_date=session_date,
                    cancelled=False,
                    source_files=sorted({r.source_file for r in rows}),
                    source_headers=sorted({r.source_header for r in rows}),
                    marks={},
                    duplicate_count=len(rows),
                    duplicate_status="BLOCK_PROGRAMME_CONFLICT",
                    blocking_reason="Same canonical activity/date came from multiple source programmes.",
                )
            )
            continue

        programme = next(iter(programme_set))
        cancel_values = {r.cancelled for r in rows}

        if len(cancel_values) > 1:
            merged.append(
                MergedSession(
                    source_programme=programme,
                    canonical_activity=activity,
                    session_date=session_date,
                    cancelled=False,
                    source_files=sorted({r.source_file for r in rows}),
                    source_headers=sorted({r.source_header for r in rows}),
                    marks={},
                    duplicate_count=len(rows),
                    duplicate_status="BLOCK_CANCELLED_DELIVERED_CONFLICT",
                    blocking_reason="Duplicate source date appears both Cancelled and Delivered.",
                )
            )
            continue

        cancelled = rows[0].cancelled

        if cancelled:
            merged.append(
                MergedSession(
                    source_programme=programme,
                    canonical_activity=activity,
                    session_date=session_date,
                    cancelled=True,
                    source_files=sorted({r.source_file for r in rows}),
                    source_headers=sorted({r.source_header for r in rows}),
                    marks={},
                    duplicate_count=len(rows),
                    duplicate_status="DEDUP_CANCELLED" if len(rows) > 1 else "UNIQUE",
                )
            )
            continue

        # For delivered source duplicates, compare exact matched mark sets.
        fingerprints = []
        for r in rows:
            fp = tuple(sorted((pid, mark.value) for pid, mark in r.marks.items()))
            fingerprints.append(fp)

        if len(set(fingerprints)) > 1:
            merged.append(
                MergedSession(
                    source_programme=programme,
                    canonical_activity=activity,
                    session_date=session_date,
                    cancelled=False,
                    source_files=sorted({r.source_file for r in rows}),
                    source_headers=sorted({r.source_header for r in rows}),
                    marks={},
                    duplicate_count=len(rows),
                    duplicate_status="BLOCK_DUPLICATE_ATTENDANCE_CONFLICT",
                    blocking_reason="Duplicate source activity/date has different matched Yes/No participant sets.",
                )
            )
            continue

        merged.append(
            MergedSession(
                source_programme=programme,
                canonical_activity=activity,
                session_date=session_date,
                cancelled=False,
                source_files=sorted({r.source_file for r in rows}),
                source_headers=sorted({r.source_header for r in rows}),
                marks=dict(rows[0].marks),
                duplicate_count=len(rows),
                duplicate_status="DEDUP_IDENTICAL" if len(rows) > 1 else "UNIQUE",
            )
        )

    return merged


def load_activities(conn):
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, name, status
            FROM activities
            ORDER BY name, id
            """
        )
        return cur.fetchall()


def map_canonical_activities(conn):
    rows = load_activities(conn)
    result = {}

    for programme, desired_name in CANONICAL_ACTIVITY.items():
        matches = [r for r in rows if norm(r["name"]) == norm(desired_name)]
        if len(matches) != 1:
            raise RuntimeError(
                f"Expected exactly one canonical activity named {desired_name!r}; found {len(matches)}."
            )
        result[programme] = matches[0]

    return result


def current_sessions_for_activity_date(conn, activity_id: str, session_date: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, activity_id, start_at, end_at, status
            FROM sessions
            WHERE activity_id = %s
              AND DATE(start_at) = %s
            ORDER BY start_at, id
            """,
            (activity_id, session_date),
        )
        return cur.fetchall()


def plan_sessions(conn, merged_sessions, activity_map, times):
    for s in merged_sessions:
        if s.blocking_reason:
            s.plan_action = "BLOCK_SOURCE_CONFLICT"
            continue

        start, end, rule = resolve_time(times, s.source_programme, s.session_date)
        s.time_start = start
        s.time_end = end
        s.time_rule = rule

        if not start or not end:
            s.plan_action = "BLOCK_MISSING_TIME"
            s.blocking_reason = rule
            continue

        start_dt = f"{s.session_date} {start}:00"
        end_dt = f"{s.session_date} {end}:00"

        if end <= start:
            s.plan_action = "BLOCK_INVALID_TIME_RANGE"
            s.blocking_reason = f"End time {end} is not after start time {start}."
            continue

        activity_id = str(activity_map[s.source_programme]["id"])
        existing = current_sessions_for_activity_date(conn, activity_id, s.session_date)

        exact = [
            row for row in existing
            if row["start_at"].strftime("%Y-%m-%d %H:%M:%S") == start_dt
            and row["end_at"].strftime("%Y-%m-%d %H:%M:%S") == end_dt
        ]

        if len(exact) == 1:
            s.plan_action = "REUSE_EXISTING_SESSION"
            s.existing_session_id = str(exact[0]["id"])
            s.session_id = str(exact[0]["id"])
            continue

        if len(exact) > 1:
            s.plan_action = "BLOCK_MULTIPLE_EXACT_EXISTING_SESSIONS"
            s.blocking_reason = f"{len(exact)} exact existing sessions found."
            continue

        if existing:
            s.plan_action = "BLOCK_EXISTING_SESSION_DIFFERENT_TIME"
            s.blocking_reason = (
                f"{len(existing)} existing session(s) already exist for this activity/date with a different time."
            )
            continue

        s.plan_action = "CREATE_SESSION"
        s.session_id = str(uuid.uuid4())


def existing_registration(conn, session_id: str, participant_id: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, booking_status, registration_source
            FROM session_registrations
            WHERE session_id=%s AND participant_id=%s
            """,
            (session_id, participant_id),
        )
        return cur.fetchall()


def existing_attendance(conn, session_id: str, participant_id: str):
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, attendance_status
            FROM attendance
            WHERE session_id=%s AND participant_id=%s
            """,
            (session_id, participant_id),
        )
        return cur.fetchall()


def write_csv(path: Path, rows: list[dict[str, Any]]):
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields = list(rows[0].keys())
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def session_audit_row(s: MergedSession):
    yes_count = sum(1 for m in s.marks.values() if m.value == "yes")
    no_count = sum(1 for m in s.marks.values() if m.value == "no")
    return {
        "source_programme": s.source_programme,
        "canonical_activity": s.canonical_activity,
        "session_date": s.session_date,
        "cancelled": "YES" if s.cancelled else "NO",
        "start_time": s.time_start or "",
        "end_time": s.time_end or "",
        "time_rule": s.time_rule,
        "duplicate_count": s.duplicate_count,
        "duplicate_status": s.duplicate_status,
        "source_files": " | ".join(s.source_files),
        "source_headers": " | ".join(s.source_headers),
        "matched_yes": yes_count,
        "matched_no": no_count,
        "plan_action": s.plan_action,
        "session_id": s.session_id or "",
        "blocking_reason": s.blocking_reason,
    }


def build_mark_plan(conn, sessions: list[MergedSession]):
    rows = []
    blocking = 0

    for s in sessions:
        if s.plan_action not in {"CREATE_SESSION", "REUSE_EXISTING_SESSION"}:
            continue
        if s.cancelled:
            continue

        for pid, mark in sorted(s.marks.items(), key=lambda x: (x[1].ocf_id, x[1].participant_name)):
            expected_booking = "Attended" if mark.value == "yes" else "NoShow"
            expected_attendance = "Present" if mark.value == "yes" else "Absent"

            if s.plan_action == "CREATE_SESSION":
                reg_action = "CREATE"
                att_action = "CREATE"
                reason = ""
            else:
                regs = existing_registration(conn, s.session_id, pid)
                atts = existing_attendance(conn, s.session_id, pid)

                if len(regs) > 1 or len(atts) > 1:
                    reg_action = "BLOCK"
                    att_action = "BLOCK"
                    reason = "Duplicate existing registration and/or attendance rows."
                    blocking += 1
                else:
                    if len(regs) == 0:
                        reg_action = "CREATE"
                    elif regs[0]["booking_status"] == expected_booking:
                        reg_action = "REUSE"
                    else:
                        reg_action = "BLOCK"
                        blocking += 1

                    if len(atts) == 0:
                        att_action = "CREATE"
                    elif atts[0]["attendance_status"] == expected_attendance:
                        att_action = "REUSE"
                    else:
                        att_action = "BLOCK"
                        blocking += 1

                    reason = ""
                    if reg_action == "BLOCK":
                        reason += f"Existing booking_status differs from {expected_booking}. "
                    if att_action == "BLOCK":
                        reason += f"Existing attendance_status differs from {expected_attendance}."

            rows.append({
                "session_date": s.session_date,
                "canonical_activity": s.canonical_activity,
                "session_id": s.session_id,
                "participant_id": pid,
                "ocf_id": mark.ocf_id,
                "participant_name": mark.participant_name,
                "source_mark": mark.value,
                "expected_booking_status": expected_booking,
                "expected_attendance_status": expected_attendance,
                "registration_action": reg_action,
                "attendance_action": att_action,
                "blocking_reason": reason.strip(),
            })

    return rows, blocking


def parse_args():
    p = argparse.ArgumentParser(description="OCF historical session/attendance migration.")
    p.add_argument("--source-dir", required=True)
    p.add_argument("--participants-csv", required=True)
    p.add_argument("--sessions-csv", required=True)
    p.add_argument("--times", required=True)
    p.add_argument("--output-dir", default=".")
    p.add_argument("--connection-string", default=DEFAULT_CONNECTION_STRING)
    p.add_argument("--commit", action="store_true")
    return p.parse_args()


def main():
    args = parse_args()

    source_dir = Path(args.source_dir).expanduser().resolve()
    participants_csv = Path(args.participants_csv).expanduser().resolve()
    sessions_csv = Path(args.sessions_csv).expanduser().resolve()
    times_path = Path(args.times).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    for p in [source_dir, participants_csv, sessions_csv, times_path]:
        if not p.exists():
            print(f"ERROR: required input not found: {p}", file=sys.stderr)
            return 2

    if "YOUR_DB_" in args.connection_string:
        print("ERROR: set OCF_MYSQL_CONNECTION_STRING first.", file=sys.stderr)
        return 3

    participant_rows = load_csv(participants_csv)
    session_rows = load_csv(sessions_csv)
    times = load_times(times_path)

    participant_index = load_participant_match_index(participant_rows)
    source_session_index = load_source_session_index(session_rows)

    source_sessions, workbook_errors = build_excel_marks(
        source_dir,
        participant_index,
        source_session_index,
    )

    merged = merge_duplicate_source_sessions(source_sessions)

    conn = connect_mysql(args.connection_string)

    try:
        activity_map = map_canonical_activities(conn)
        plan_sessions(conn, merged, activity_map, times)
        mark_plan, mark_blocks = build_mark_plan(conn, merged)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        mode = "commit" if args.commit else "preview"
        prefix = output_dir / f"ocf_session_attendance_{mode}_{timestamp}"

        session_csv_out = Path(str(prefix) + "_sessions.csv")
        marks_csv_out = Path(str(prefix) + "_marks.csv")
        errors_csv_out = Path(str(prefix) + "_workbook_errors.csv")

        write_csv(session_csv_out, [session_audit_row(s) for s in merged])
        write_csv(marks_csv_out, mark_plan)
        write_csv(errors_csv_out, workbook_errors)

        session_counts = Counter(s.plan_action for s in merged)
        duplicate_counts = Counter(s.duplicate_status for s in merged)
        registration_counts = Counter(r["registration_action"] for r in mark_plan)
        attendance_counts = Counter(r["attendance_action"] for r in mark_plan)

        blocking_sessions = [
            s for s in merged
            if s.plan_action.startswith("BLOCK")
        ]

        print()
        print("OCF Historical Sessions + Attendance Migration")
        print("----------------------------------------------")
        print(f"Source session columns included:       {len(source_sessions)}")
        print(f"Canonical activity/date sessions:      {len(merged)}")
        print(f"Identical duplicate dates deduplicated:{duplicate_counts['DEDUP_IDENTICAL']}")
        print(f"Cancelled duplicate dates deduplicated:{duplicate_counts['DEDUP_CANCELLED']}")
        print()
        print("Session plan")
        print(f"  Create sessions:                     {session_counts['CREATE_SESSION']}")
        print(f"  Reuse exact existing sessions:       {session_counts['REUSE_EXISTING_SESSION']}")
        print(f"  Blocking session/time conflicts:     {len(blocking_sessions)}")
        print()
        print("Matched historical marks")
        print(f"  Registration CREATE:                 {registration_counts['CREATE']}")
        print(f"  Registration REUSE:                  {registration_counts['REUSE']}")
        print(f"  Registration BLOCK:                  {registration_counts['BLOCK']}")
        print(f"  Attendance CREATE:                   {attendance_counts['CREATE']}")
        print(f"  Attendance REUSE:                    {attendance_counts['REUSE']}")
        print(f"  Attendance BLOCK:                    {attendance_counts['BLOCK']}")
        print()
        print(f"Workbook/header errors:                {len(workbook_errors)}")
        print()
        print("Audit files:")
        print(f"  {session_csv_out}")
        print(f"  {marks_csv_out}")
        if workbook_errors:
            print(f"  {errors_csv_out}")
        print()

        if workbook_errors:
            conn.rollback()
            print("STOP: workbook/header errors exist. Database was NOT changed.")
            return 10

        if blocking_sessions or mark_blocks:
            conn.rollback()
            print("STOP: blocking session/time/attendance conflicts exist. Database was NOT changed.")
            print("Review the *_sessions.csv and *_marks.csv files.")
            return 11

        if not args.commit:
            conn.rollback()
            print("PREVIEW COMPLETE: database was NOT changed.")
            return 0

        # ------------------------------------------------------------
        # COMMIT
        # ------------------------------------------------------------
        conn.begin()
        try:
            # Create sessions first.
            for s in merged:
                if s.plan_action != "CREATE_SESSION":
                    continue

                activity_id = str(activity_map[s.source_programme]["id"])
                start_at = f"{s.session_date} {s.time_start}:00"
                end_at = f"{s.session_date} {s.time_end}:00"
                status = "Cancelled" if s.cancelled else "Delivered"

                notes = (
                    f"{MIGRATION_NAME}; source programme={s.source_programme}; "
                    f"source files={'; '.join(s.source_files)}; "
                    f"source headers={'; '.join(s.source_headers)}"
                )

                with conn.cursor() as cur:
                    # Recheck for exact session inside transaction.
                    cur.execute(
                        """
                        SELECT id, start_at, end_at, status
                        FROM sessions
                        WHERE activity_id=%s
                          AND DATE(start_at)=%s
                        ORDER BY start_at, id
                        """,
                        (activity_id, s.session_date),
                    )
                    current = cur.fetchall()

                    exact = [
                        r for r in current
                        if r["start_at"].strftime("%Y-%m-%d %H:%M:%S") == start_at
                        and r["end_at"].strftime("%Y-%m-%d %H:%M:%S") == end_at
                    ]

                    if len(exact) == 1:
                        s.session_id = str(exact[0]["id"])
                    elif current:
                        raise RuntimeError(
                            f"Session conflict appeared during commit for {s.canonical_activity} {s.session_date}."
                        )
                    else:
                        cur.execute(
                            """
                            INSERT INTO sessions
                                (
                                    id,
                                    activity_id,
                                    assigned_staff_id,
                                    start_at,
                                    end_at,
                                    status,
                                    capacity,
                                    notes
                                )
                            VALUES
                                (%s, %s, NULL, %s, %s, %s, NULL, %s)
                            """,
                            (
                                s.session_id,
                                activity_id,
                                start_at,
                                end_at,
                                status,
                                notes,
                            ),
                        )

            # Rebuild mark plan now that all created sessions exist.
            mark_plan, mark_blocks = build_mark_plan(conn, merged)
            if mark_blocks:
                raise RuntimeError("Registration/attendance conflict appeared during commit.")

            for row in mark_plan:
                session_id = row["session_id"]
                participant_id = row["participant_id"]

                if row["registration_action"] == "CREATE":
                    with conn.cursor() as cur:
                        cur.execute(
                            """
                            SELECT id, booking_status
                            FROM session_registrations
                            WHERE session_id=%s AND participant_id=%s
                            """,
                            (session_id, participant_id),
                        )
                        current = cur.fetchall()

                        if not current:
                            cur.execute(
                                """
                                INSERT INTO session_registrations
                                    (
                                        id,
                                        session_id,
                                        participant_id,
                                        booking_status,
                                        registration_source
                                    )
                                VALUES
                                    (%s, %s, %s, %s, 'ActivityType')
                                """,
                                (
                                    str(uuid.uuid4()),
                                    session_id,
                                    participant_id,
                                    row["expected_booking_status"],
                                ),
                            )
                        elif len(current) != 1 or current[0]["booking_status"] != row["expected_booking_status"]:
                            raise RuntimeError(
                                f"Registration conflict during commit for session={session_id}, participant={participant_id}."
                            )

                if row["attendance_action"] == "CREATE":
                    with conn.cursor() as cur:
                        cur.execute(
                            """
                            SELECT id, attendance_status
                            FROM attendance
                            WHERE session_id=%s AND participant_id=%s
                            """,
                            (session_id, participant_id),
                        )
                        current = cur.fetchall()

                        if not current:
                            attended_at = None
                            if row["expected_attendance_status"] == "Present":
                                # Historical Present time is the session start time.
                                cur.execute(
                                    "SELECT start_at FROM sessions WHERE id=%s",
                                    (session_id,),
                                )
                                attended_at = cur.fetchone()["start_at"]

                            cur.execute(
                                """
                                INSERT INTO attendance
                                    (
                                        id,
                                        session_id,
                                        participant_id,
                                        attendance_status,
                                        attended_at,
                                        recorded_by
                                    )
                                VALUES
                                    (%s, %s, %s, %s, %s, NULL)
                                """,
                                (
                                    str(uuid.uuid4()),
                                    session_id,
                                    participant_id,
                                    row["expected_attendance_status"],
                                    attended_at,
                                ),
                            )
                        elif len(current) != 1 or current[0]["attendance_status"] != row["expected_attendance_status"]:
                            raise RuntimeError(
                                f"Attendance conflict during commit for session={session_id}, participant={participant_id}."
                            )

            conn.commit()

        except Exception:
            conn.rollback()
            raise

        print("COMMIT COMPLETE.")
        print("Historical sessions, session registrations and attendance were migrated.")
        print("No participant, Activity Type, Activity or participant allocation records were changed.")
        return 0

    except Exception as exc:
        try:
            conn.rollback()
        except Exception:
            pass
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
